### ISSUE TITLE
Paging through the ModalPicker

### ISSUE THREAD

**Issue by devpascoe** [thinkproductivity/emoji-mart-native#47] opened 2018-10-15 22:03 UTC
Perhaps i'm overlaying over too many views or something but i have found the ModalPicker to be way too sensitive on detecting touches when paging through emojis. A swipe is easily mistaken for a touch and selects an emoji instead of scrolling to the next page.
In addition i am using local images for the emoji sheets however there seems to be a delay in paging through the ModalPicker still. I have to page waiting a good moment or two between swipes.

**Comment by pederjohnsen** [comment] 2018-10-16 13:01
Hey @devpascoe!

Is the swipe/touch issue happening on iOS, Android or both?

With your second issue, I'm not 100% sure I understand what the issue is, you should be able to swipe to the next page regardless whether the page of emojis have finished loading or not (if the emojis are taking a long time to render, it is likely local requires is not set up correctly, sharing some of your code would be helpful here)

**Comment by pederjohnsen** [comment] 2018-11-05 09:20
@devpascoe thanks for reply, first thing I want to note is that some of the customization is not yet properly tested or supported so it's possible they could be causing some issues. (`style`/`perLine`/`emojiSize`)

As you say you are using a `FlatList` as the root view, are you rendering the `ModalPicker` inside it? Not sure but potentially this could also be causing issues.. I will try do some testing soon, thanks for all the extra info you provided :+1:

**Comment by devpascoe** [comment] 2018-11-23 01:47
Hi there, thought i'd check in. So all my problems went away when i replaced:
set="apple"
data={data}
useLocalImages={localEmojis}

with

native={true}

**Comment by pederjohnsen** [comment] 2018-11-25 22:12
@devpascoe thanks for the update, I've been doing some testing but so far have been unable to reproduce the issues you described :thinking:

It'd be interesting to know if you also get those issues using our example app if you ever have time to test :confused:

Only problem with using native is if on an older device certain emojis probably won't show properly, and could potentially cause layout issues.

**Comment by johnsenpeder** [comment] 2019-03-08 10:16
Closing for now as I've been unable to replicate and author found a work around.

**Closed by johnsenpeder** 2019-03-08 10:16 UTC
Labels: question
